### ISSUE TITLE
Bad color config example values in README

### ISSUE THREAD

**Issue by leoj3n** [kulpae/cloudruby#18]
Any of these:

~~~
      "title": ["cyan"],
      "artist": ["magenta"],
      "status": ["red"]
~~~

Cause this:

~~~
#<NoMethodError: undefined method `to_sym' for -1:Fixnum>
~/.rvm/gems/ruby-2.2.1/gems/cloudruby-1.2.0/lib/ncurses_ui.rb:333:in `ncg'
~/.rvm/gems/ruby-2.2.1/gems/cloudruby-1.2.0/lib/ncurses_ui.rb:297:in `add'
~/.rvm/gems/ruby-2.2.1/gems/cloudruby-1.2.0/lib/ncurses_ui.rb:288:in `block in init'
~/.rvm/gems/ruby-2.2.1/gems/cloudruby-1.2.0/lib/ncurses_ui.rb:287:in `each'
~/.rvm/gems/ruby-2.2.1/gems/cloudruby-1.2.0/lib/ncurses_ui.rb:287:in `init'
~/.rvm/gems/ruby-2.2.1/gems/cloudruby-1.2.0/lib/ncurses_ui.rb:53:in `run'
~/.rvm/gems/ruby-2.2.1/gems/cloudruby-1.2.0/lib/cloudruby.rb:87:in `run'
~/.rvm/gems/ruby-2.2.1/gems/cloudruby-1.2.0/bin/cloudruby:47:in `<top (required)>'
~/.rvm/gems/ruby-2.2.1/bin/cloudruby:23:in `load'
~/.rvm/gems/ruby-2.2.1/bin/cloudruby:23:in `<main>'
~/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
~/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'
~~~

However the example for the crimson theme in `doc/colors.md` worked fine.

**Comment by kulpae** [comment]
Indeed, there is a regression. I'll fix the code and let the README as is. Thank you for bug report.
